management:
  endpoint.health:
    probes.enabled: true
    show-components: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
      path-mapping:
        health: health
        prometheus: prometheus
      base-path: /
